[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/historico.py"
name = "HistÃ³rico"
icon = "ğŸ—‚ï¸"
url_path = "historico" 

[[pages]]
path = "pages/upload.py"
name = "Upload"
icon = "ğŸ“¤"
url_path = "upload" 

[[pages]]
path = "pages/configuracoes.py"
name = "ConfiguraÃ§Ãµes"
icon = "âš™ï¸"
url_path = "configuracoes"